name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Runs when you push changes to the master branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetches your repo code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Enables advanced Docker builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.gopali }}
          password: ${{ secrets.Garggopali1987 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gopali/gift_card_csharp_postgres:latest